const products = [
	{
		id: 1,
		name: 'Clausing Lathe',
		src: 'clausing-lathe.png',
		type: 'equipment',
		status: '',
		manufacturer: 'Clausing',
		modelNumber: 'XYZ-123',
		yearManufactured: 2020,
		location: 'Workshop A',
		maintenanceSchedule: 'Quarterly',
		purchaseDate: '2020-05-15',
		purchasePrice: 5000,
		warrantyExpires: '2022-05-15',
		powerRequirements: '290V, 3-phase',
		weight: '1800 kg',
		usageHours: 1200,
	},
	{
		id: 2,
		name: 'Die Spotting Machine',
		src: 'die-spotting-machine.png',
		type: 'equipment',
		status: '',
		manufacturer: 'ABC Manufacturing',
		modelNumber: 'DSM-2000',
		yearManufactured: 2021,
		location: 'Factory Floor',
		maintenanceSchedule: 'Bi-Annual',
		purchaseDate: '2021-08-20',
		purchasePrice: 10000,
		warrantyExpires: '2023-08-20',
		powerRequirements: '220V, 3-phase',
		weight: '1500 kg',
		usageHours: 1200,
	},
	{
		id: 3,
		name: 'Economical Fiber Laser',
		src: 'economical-fiber-laser.png',
		type: 'equipment',
		status: '',
		manufacturer: 'Tech Laser Inc.',
		modelNumber: 'EFL-200',
		yearManufactured: 2023,
		location: 'Production Area 1',
		maintenanceSchedule: 'Monthly',
		purchaseDate: '2023-05-10',
		purchasePrice: 25000,
		warrantyExpires: '2025-05-10',
		powerRequirements: '110V, Single-phase',
		weight: '500 kg',
		usageHours: 800,
	},
	{
		id: 4,
		name: 'Engraving CNC Machine',
		src: 'engraving-cnc-machine.png',
		type: 'equipment',
		status: '',
		manufacturer: 'Precision Machining Solutions',
		modelNumber: 'CNC-Engrave-5000',
		yearManufactured: 2022,
		location: 'Workshop B',
		maintenanceSchedule: 'Quarterly',
		purchaseDate: '2022-07-20',
		purchasePrice: 18000,
		warrantyExpires: '2024-07-20',
		powerRequirements: '220V, 3-phase',
		weight: '1200 kg',
		usageHours: 1200,
	},
	{
		id: 5,
		name: 'Geared Head Drill Press',
		src: 'geared-head-drill-press.png',
		type: 'equipment',
		status: '',
		manufacturer: 'DrillMaster Inc.',
		modelNumber: 'GHDP-300',
		yearManufactured: 2021,
		location: 'Tool Room',
		maintenanceSchedule: 'Bi-Annual',
		purchaseDate: '2021-10-05',
		purchasePrice: 5000,
		warrantyExpires: '2023-10-05',
		powerRequirements: '240V, Single-phase',
		weight: '300 kg',
		usageHours: 600,
	},
	{
		id: 6,
		name: 'Heat Treat Oven',
		src: 'heat-treat-oven.png',
		type: 'equipment',
		status: '',
		manufacturer: 'HeatPro Engineering',
		modelNumber: 'HTO-600',
		yearManufactured: 2020,
		location: 'Heat Treatment Area',
		maintenanceSchedule: 'Annual',
		purchaseDate: '2020-03-15',
		purchasePrice: 15000,
		warrantyExpires: '2022-03-15',
		powerRequirements: '380V, 3-phase',
		weight: '2000 kg',
		usageHours: 2000,
	},
	{
		id: 7,
		name: 'Hole Drilling Machine',
		src: 'hole-drilling-machine.png',
		type: 'equipment',
		status: '',
		manufacturer: 'DrillTech Industries',
		modelNumber: 'HD-1000',
		yearManufactured: 2023,
		location: 'Production Area 2',
		maintenanceSchedule: 'Monthly',
		purchaseDate: '2023-02-28',
		purchasePrice: 12000,
		warrantyExpires: '2025-02-28',
		powerRequirements: '240V, Single-phase',
		weight: '800 kg',
		usageHours: 1000,
	},
	{
		id: 8,
		name: 'Honing Machine',
		src: 'honing-machine.png',
		type: 'equipment',
		status: '',
		manufacturer: 'HoneMaster Inc.',
		modelNumber: 'HM-500',
		yearManufactured: 2022,
		location: 'Workshop C',
		maintenanceSchedule: 'Bi-Annual',
		purchaseDate: '2022-11-10',
		purchasePrice: 20000,
		warrantyExpires: '2024-11-10',
		powerRequirements: '440V, 3-phase',
		weight: '1500 kg',
		usageHours: 800,
	},
	{
		id: 9,
		name: 'Laser Cube',
		src: 'laser-cube.png',
		type: 'equipment',
		status: '',
		manufacturer: 'LaserTech Solutions',
		modelNumber: 'LC-1000',
		yearManufactured: 2021,
		location: 'Laser Cutting Room',
		maintenanceSchedule: 'Quarterly',
		purchaseDate: '2021-04-25',
		purchasePrice: 30000,
		warrantyExpires: '2023-04-25',
		powerRequirements: '380V, 3-phase',
		weight: '700 kg',
		usageHours: 1500,
	},
	{
		id: 10,
		name: 'Lathe',
		src: 'lathe.png',
		type: 'equipment',
		status: '',
		manufacturer: 'LatheMaster Inc.',
		modelNumber: 'LM-100',
		yearManufactured: 2023,
		location: 'Workshop D',
		maintenanceSchedule: 'Quarterly',
		purchaseDate: '2023-09-15',
		purchasePrice: 18000,
		warrantyExpires: '2025-09-15',
		powerRequirements: '220V, 3-phase',
		weight: '1000 kg',
		usageHours: 1000,
	},
	{
		id: 11,
		name: 'MIG Welder Kit',
		src: 'mig-welder-kit.png',
		type: 'equipment',
		status: '',
		manufacturer: 'WeldTech',
		modelNumber: 'MIG-2000',
		yearManufactured: 2023,
		location: 'Welding Area',
		maintenanceSchedule: 'Bi-Annual',
		purchaseDate: '2023-04-15',
		purchasePrice: 5000,
		warrantyExpires: '2025-04-15',
		powerRequirements: '220V, 3-phase',
		weight: '800 kg',
		usageHours: 500,
	},
	{
		id: 12,
		name: 'Muffle Furnace',
		src: 'muffle-furnace.png',
		type: 'equipment',
		status: '',
		manufacturer: 'HeatMaster',
		modelNumber: 'MF-500',
		yearManufactured: 2022,
		location: 'Heat Treatment Lab',
		maintenanceSchedule: 'Annual',
		purchaseDate: '2022-06-20',
		purchasePrice: 8000,
		warrantyExpires: '2024-06-20',
		powerRequirements: '380V, 3-phase',
		weight: '600 kg',
		usageHours: 300,
	},
	{
		id: 13,
		name: 'OxyAcetylene Kit',
		src: 'oxyacetylene-kit.png',
		type: 'equipment',
		status: '',
		manufacturer: 'FlameTech',
		modelNumber: 'OA-100',
		yearManufactured: 2021,
		location: 'Welding Area',
		maintenanceSchedule: 'Quarterly',
		purchaseDate: '2021-10-10',
		purchasePrice: 2000,
		warrantyExpires: '2023-10-10',
		gasType: 'Oxy-Acetylene',
		tankCapacity: '20 cubic feet',
		torchType: 'Cutting and Welding',
		usageHours: 200,
	},
	{
		id: 14,
		name: 'Push Press',
		src: 'push-press.png',
		type: 'equipment',
		status: '',
		manufacturer: 'PressTech',
		modelNumber: 'PP-300',
		yearManufactured: 2023,
		location: 'Production Area',
		maintenanceSchedule: 'Bi-Annual',
		purchaseDate: '2023-02-15',
		purchasePrice: 10000,
		warrantyExpires: '2025-02-15',
		powerRequirements: '440V, 3-phase',
		weight: '1200 kg',
		usageHours: 400,
	},
	{
		id: 15,
		name: 'Surface Grinder',
		src: 'surface-grinder.png',
		type: 'equipment',
		status: '',
		manufacturer: 'GrindTech',
		modelNumber: 'SG-500',
		yearManufactured: 2022,
		location: 'Grinding Room',
		maintenanceSchedule: 'Monthly',
		purchaseDate: '2022-04-30',
		purchasePrice: 15000,
		warrantyExpires: '2024-04-30',
		powerRequirements: '220V, 3-phase',
		weight: '1500 kg',
		usageHours: 800,
	},
	{
		id: 16,
		name: 'Surface Grinder Saddle Type',
		src: 'surface-grinder-saddle-type.png',
		type: 'equipment',
		status: '',
		manufacturer: 'GrindTech',
		modelNumber: 'SGS-700',
		yearManufactured: 2023,
		location: 'Grinding Room',
		maintenanceSchedule: 'Monthly',
		purchaseDate: '2023-08-20',
		purchasePrice: 18000,
		warrantyExpires: '2025-08-20',
		powerRequirements: '220V, 3-phase',
		weight: '2000 kg',
		usageHours: 600,
	},
	{
		id: 17,
		name: 'Turning Machine',
		src: 'turning-machine.png',
		type: 'equipment',
		status: '',
		manufacturer: 'TurnTech',
		modelNumber: 'TM-200',
		yearManufactured: 2021,
		location: 'Turning Area',
		maintenanceSchedule: 'Quarterly',
		purchaseDate: '2021-07-10',
		purchasePrice: 12000,
		warrantyExpires: '2023-07-10',
		powerRequirements: '380V, 3-phase',
		weight: '1800 kg',
		usageHours: 1000,
	},
	{
		id: 18,
		name: 'Vertical Handsaw',
		src: 'vertical-bandsaw.png',
		type: 'equipment',
		status: '',
		manufacturer: 'SawMaster',
		modelNumber: 'VH-300',
		yearManufactured: 2020,
		location: 'Cutting Area',
		maintenanceSchedule: 'Bi-Annual',
		purchaseDate: '2020-09-15',
		purchasePrice: 5000,
		warrantyExpires: '2022-09-15',
		powerRequirements: '220V, Single-phase',
		weight: '400 kg',
		usageHours: 1200,
	},
	{
		id: 19,
		name: 'Vertical Machining Center',
		src: 'vertical-machining-center.png',
		type: 'equipment',
		status: '',
		manufacturer: 'MachTech',
		modelNumber: 'VMC-1000',
		yearManufactured: 2022,
		location: 'CNC Room',
		maintenanceSchedule: 'Quarterly',
		purchaseDate: '2022-11-20',
		purchasePrice: 30000,
		warrantyExpires: '2024-11-20',
		powerRequirements: '440V, 3-phase',
		weight: '2500 kg',
		usageHours: 600,
	},
	{
		id: 20,
		name: 'Vertical Mills',
		src: 'vertical-mills.png',
		type: 'equipment',
		status: '',
		manufacturer: 'MillTech',
		modelNumber: 'VM-500',
		yearManufactured: 2023,
		location: 'Milling Area',
		maintenanceSchedule: 'Monthly',
		purchaseDate: '2023-05-10',
		purchasePrice: 25000,
		warrantyExpires: '2025-05-10',
		powerRequirements: '380V, 3-phase',
		weight: '2000 kg',
		usageHours: 700,
	},
	{
		id: 21,
		name: 'Allen Key Set',
		src: 'allen-key-set.png',
		type: 'tool',
		status: 'available',
		brand: 'ToolPro',
		material: 'Steel',
		quantity: 10,
		price: 12.99,
	},
	{
		id: 22,
		name: 'Ball Peen Hammer',
		src: 'ball-peen-hammer.png',
		type: 'tool',
		status: 'in use',
		brand: 'HammerTech',
		material: 'Steel',
		quantity: 1,
		price: 8.49,
	},
	{
		id: 23,
		name: 'Caliper',
		src: 'caliper.png',
		type: 'tool',
		status: 'out of stock',
		brand: 'Precision Instruments',
		material: 'Stainless Steel',
		quantity: 1,
		price: 29.99,
	},
	{
		id: 24,
		name: 'Center Punch',
		src: 'center-punch.png',
		type: 'tool',
		status: 'maintenance required',
		brand: 'PunchMaster',
		material: 'Steel',
		quantity: 1,
		price: 5.99,
	},
	{
		id: 25,
		name: 'Combination Square Set',
		src: 'combination-square-set.png',
		type: 'tool',
		status: 'available',
		brand: 'SquareMaster',
		material: 'Aluminum',
		quantity: 1,
		price: 34.99,
	},
	{
		id: 26,
		name: 'Dial Indicator',
		src: 'dial-indicator.png',
		type: 'tool',
		status: 'in use',
		brand: 'DialPro',
		material: 'Steel',
		quantity: 1,
		price: 19.99,
	},
	{
		id: 27,
		name: 'Drill',
		src: 'drill.png',
		type: 'tool',
		status: 'available',
		brand: 'DrillMaster',
		material: 'Steel',
		quantity: 1,
		price: 49.99,
	},
	{
		id: 28,
		name: 'Edge Finder',
		src: 'edge-finder.png',
		type: 'tool',
		status: 'available',
		brand: 'EdgeTech',
		material: 'Steel',
		quantity: 1,
		price: 14.99,
	},
	{
		id: 29,
		name: 'Hammer',
		src: 'hammer.png',
		type: 'tool',
		status: 'available',
		brand: 'HammerTech',
		material: 'Steel',
		quantity: 1,
		price: 7.99,
	},
	{
		id: 30,
		name: 'Micrometer',
		src: 'micrometer.png',
		type: 'tool',
		status: 'available',
		brand: 'Precision Instruments',
		material: 'Carbide',
		quantity: 1,
		price: 39.99,
	},
	{
		id: 31,
		name: 'Plier',
		src: 'plier.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 6.99,
	},
	{
		id: 32,
		name: 'Pry Bar',
		src: 'pry-bar.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 9.99,
	},
	{
		id: 33,
		name: 'Screwdriver',
		src: 'screwdriver.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 3.99,
	},
	{
		id: 34,
		name: 'Tape Measure',
		src: 'tape-measure.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 11.99,
	},
	{
		id: 35,
		name: 'Telescoping Gage Set',
		src: 'telescoping-gage-set.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 24.99,
	},
	{
		id: 36,
		name: 'Thread Pitch Gauge',
		src: 'thread-pitch-gauge.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 8.99,
	},
	{
		id: 37,
		name: 'Thread Wires',
		src: 'thread-wires.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 5.49,
	},
	{
		id: 38,
		name: 'Transfer Punch Set',
		src: 'transfer-punch-set.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 18.99,
	},
	{
		id: 39,
		name: 'Wrench',
		src: 'wrench.png',
		type: 'tool',
		status: 'available',
		brand: 'Generic',
		material: 'Steel',
		quantity: 1,
		price: 10.99,
	},
];

export default products;
